### ISSUE TITLE
Side Bar

### ISSUE THREAD

**Issue by ifiguer** [Cap-Size/isusecSiteBeta#5]
You can see the content of the side bar collapse to the left as the side bar closes. Upon closer inspection this seems to be because opening and closing the sidebar is done by changing the width, and as the width changes the browser re-renders the content within. A solution can be to change the position of the sidebar to be off the page rather than changing the width. In this way the width of the sidebar does not change and the browser does not need to re-render.

**Comment by Cap-Size** [comment]
What do you mean by moving the sidebar off the page, like a fixed side bar?

**Comment by ifiguer** [comment]
So a fixed sidebar, like we have now, has a property `left`. This is normally set to 0, if you want the sidebar to be flush with the left border of the page. However, you can set it to a negative number, therefore moving off to the left of the left border of the page. Specifically, if this negative number is the width of the navbar, the navbar will live to the left of the page. And when we want to actually see it, you can simply remove that `left` propery, and the navbar will be visible.
