### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by ifiguer** [Cap-Size/isusecSiteBeta#8]
There's duplicate code on various files. For instance, the navbar is defined in each of the HTML files inside of `sub/`. Now that we are using Jekyll, the navbar should be included in a base layout that other files can then extend.

**Comment by Cap-Size** [comment]
This also includes code that isn't duplicate but code that isn't relevant anymore.

**Comment by ifiguer** [comment]
I forgot to link to this when I pushed the code, so see commit [Remove redundant code](https://github.com/Cap-Size/isusecSiteBeta/commit/d677b481ec2b1629a56656cb5a6b88c38a2840ff).

I also took this as an opportunity to extract `master.scss` into multiple but smaller files, under `_sass/`, and make use of variables for colors and font stack.
